# Generated by Django 6.0.2 on 2026-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
