# Generated by Django 6.0.2 on 2026-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='checklist',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
